

spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: https://www.baidu.com
          predicates:
            - Path=/baidu
            # - Cookie=mycookie,mycookievalue

